  CREATE TABLE "ISAP"."IS_ASIENTOS_CABEZAL_SAP" 
   (	"LOTE" NUMBER(10,0) NOT NULL ENABLE, 
	"BELNR" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ASIENTO_SAP" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FCREA" DATE NOT NULL ENABLE, 
	"UCREA" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FACT" DATE, 
	"UACT" VARCHAR2(30 BYTE), 
	 CONSTRAINT "PK_ASCS" PRIMARY KEY ("LOTE", "BELNR", "ASIENTO_SAP")