CREATE TABLE "SIAB"."PUB_CONV_MONEDAS" 
   (	"MONEDA_CEPRE" NUMBER(3,0) NOT NULL ENABLE, 
	"MONEDA_IMM" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FCREA" DATE NOT NULL ENABLE, 
	"UCREA" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FACT" DATE, 
	"UACT" VARCHAR2(30 BYTE), 
	 CONSTRAINT "PUMO_PK" PRIMARY KEY ("MONEDA_CEPRE"))